name: docker-publish

on:
  push:
    branches:
      - '*'
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: image-name
        id: image-name
        shell: bash
        run: |
          IMAGE_NAME="$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=image_name::${IMAGE_NAME}"
          echo "::set-output name=tags::ghcr.io/${IMAGE_NAME}:${{ github.ref_name }}"
      - name: metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ steps.image-name.outputs.image_name }}

      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.image-name.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
